### ISSUE TITLE
Is macos M1 supported?

### ISSUE THREAD

**Issue by cheprus** [ndonkoHenri/Flet-as-System-Tray-Icon#4]
Hello, TheEthicalBoy,
Is macos M1 supported? As I receive the Exception: NotImplementedError 

```
Traceback (most recent call last):
  File "/Users/chep/dev/python/jitsi_ring_bot/tmp/Flet-as-System-Tray-Icon/main.py", line 173, in <module>
    tray_icon.run_detached(setup=my_setup)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pystray/_base.py", line 231, in run_detached
    self._run_detached()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pystray/_darwin.py", line 124, in _run_detached
    raise NotImplementedError()
NotImplementedError
```
from this part of code
```
 def _run_detached(self):
        if self._detachable:
            self._mark_ready()
        else:
            raise NotImplementedError()
```

**Comment by ndonkoHenri** [comment]
I guess it isn't.

Give pystray docs a look.
